# Generated by Django 4.2 on 2025-04-22 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_alter_portfolio_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'portfolio', 'verbose_name_plural': 'portfolios'},
        ),
    ]
