# Generated by Django 4.2 on 2025-04-26 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0003_alter_portfolio_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='permission',
            field=models.CharField(choices=[('ADMIN', 'administrator'), ('MODER', 'moderator'), ('STUDENT', 'student'), ('USER', 'user')], default='USER', max_length=15),
        ),
    ]
