# Generated by Django 5.1.7 on 2025-05-01 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0005_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
