# Generated by Django 5.1.7 on 2025-05-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_image_content_alter_image_created_by_and_more'),
        ('gallery', '0004_image_is_approved_alter_image_content_and_more'),
    ]

    operations = [
    ]
