# Generated by Django 5.2 on 2025-05-17 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_merge_20250517_1645'),
        ('gallery', '0006_alter_image_image'),
    ]

    operations = [
    ]
