# Generated by Django 5.1.4 on 2025-05-15 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='date',
            field=models.DateTimeField(default=now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='creator',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
