# Generated by Django 5.1.7 on 2025-05-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ('-changed_at',), 'verbose_name': 'material', 'verbose_name_plural': 'materials'},
        ),
    ]
