# Generated by Django 5.1.4 on 2025-04-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='title',
            field=models.CharField(max_length=36, null=True),
        ),
    ]
