# Generated by Django 5.1.4 on 2025-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcement', '0002_announcement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Untitled', max_length=36),
            preserve_default=False,
        ),
    ]
