# Generated by Django 5.1.7 on 2025-05-09 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_post_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx', 'png', 'jpg', 'jpeg'])]),
        ),
    ]
