# Generated by Django 5.1.7 on 2025-05-09 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_thread_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
