# Generated by Django 5.1.4 on 2025-05-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveycomment',
            old_name='content',
            new_name='comment',
        ),
    ]
