# Generated by Django 5.1.4 on 2025-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_surveycomment_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='max_comments',
            field=models.PositiveIntegerField(default=10, help_text='Сколько ответов принимается, прежде чем опрос закрыт'),
        ),
    ]
